### ISSUE TITLE
World Building Checklist

### ISSUE THREAD

**Issue by LordEggNutz** [LordEggNutz/Imrallon#38]
World Building Checklist for Imrallon.  Comments will have details
- [ ] Day/Night Cycle Length
- [ ] Physics / Gravity
- [ ] Sky / Grass / Water color
- [ ] Number of Moons
- [ ] Number of Landmasses
- [ ] Bodies of Water
- [ ] Mountain Ranges
- [ ] Natural Resources
- [ ] Rituals and Holidays
- [ ] Seasons and Natural Wonders
- [ ] History and Religion
- [ ] Technology and Magic
- [ ] Notable Flora and Fauna
- [ ] Imports / Exports
- [ ] Political Structure
- [ ] Education
- [ ] Great Cities and Buildings
- [ ] Biology and Procreation
- [ ] Family Life and Structure
- [ ] Gender Roles
- [ ] Genealogy
- [ ] Languages
- [ ] Work Life
- [ ] Warfare Tactics
- [ ] Arts and Entertainment
- [ ] Fashion and Cuisine
- [ ] Unexplainable Wonders
- [ ] Illicit Substances
- [ ] Weather Patterns / Anomalies 
- [ ] Races
- [ ] Finance / Economic System
- [ ] Legal System

**Comment by LordEggNutz** [comment]
### Number of Moons

Imrallon has a pair of moons that circle the planet.  

- Moon 1 - Vreox is a dark blue moonthat is only visible in the day time and sheds a faint violet glow across its shadow.
- Moon 2 - Stria is a dull yellowish moon that is only visible during the day. 

Each moon is significant in various local festivities, rituals and holidays.
